version: "3.9"
services:
    pkg:
        build: 
            context: .
            dockerfile: Dockerfile.local
        container_name: userservice
        ports:
            - "0.0.0.0:5002:5002"
        depends_on:
            - user_db
    user_db:
        image: "mcr.microsoft.com/mssql/server"
        volumes:
          - user_volume:/var/opt/mssql

        environment:
            SA_PASSWORD: "Semester6"
            ACCEPT_EULA: "Y"
        ports:
            - "1433"
            - "1002:1433"
volumes:
  user_volume:
