version: "3.9"
services:
    user_db:
        image: "mcr.microsoft.com/mssql/server"
        volumes:
          - UserVolume:/var/opt/mssql

        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433"
            - "1002:1433"
volumes:
  UserVolume:
